# Generated by Django 3.0.8 on 2021-07-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=200)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga_of_origin', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=400)),
                ('residential_lga', models.CharField(max_length=200)),
                ('residential_state', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_account_no', models.CharField(max_length=200)),
                ('image_of_rider', models.ImageField(blank=True, default='profile1.png', upload_to='')),
                ('qualification', models.CharField(max_length=200)),
                ('date_of_appointment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiderAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_tracking_id', models.CharField(max_length=22)),
                ('date_and_time_of_assignment', models.DateTimeField(auto_now_add=True)),
                ('rider_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.RiderRecord')),
            ],
        ),
    ]
